"""add_contrato_historico_table

Revision ID: 0191717a7693
Revises: e0ff80644a3e
Create Date: 2026-04-06 14:17:56.154733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0191717a7693'
down_revision: Union[str, Sequence[str], None] = 'e0ff80644a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_historico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False, comment='Autor da ação (temporário até JWT).'),
    sa.Column('tipo_registro', sa.Enum('Edição de Sistema', 'Observação Manual', name='tipo_registro_historico_enum'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False, comment='Descrição da mudança ou texto da observação.'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrato_historico_contrato_id'), 'contrato_historico', ['contrato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrato_historico_contrato_id'), table_name='contrato_historico')
    op.drop_table('contrato_historico')
    # ### end Alembic commands ###
