"""add_vigencia_to_item_contrato

Revision ID: 02d5934d6803
Revises: 390b919c1902
Create Date: 2026-05-18 14:55:13.813598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d5934d6803'
down_revision: Union[str, Sequence[str], None] = '390b919c1902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_contrato', sa.Column('data_inicio_vigencia', sa.Date(), nullable=True, comment='Data de início do suporte/garantia específico do item.'))
    op.add_column('item_contrato', sa.Column('data_fim_vigencia', sa.Date(), nullable=True, comment='Data de fim do suporte/garantia específico do item.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_contrato', 'data_fim_vigencia')
    op.drop_column('item_contrato', 'data_inicio_vigencia')
    # ### end Alembic commands ###
