"""add projeto_tramitacao log

Revision ID: 14c7f43da8b0
Revises: 3c9029f7bd3f
Create Date: 2026-04-08 18:01:55.145057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c7f43da8b0'
down_revision: Union[str, Sequence[str], None] = '3c9029f7bd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto_tramitacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False, comment='Descrição do andamento/tramitação na licitação.'),
    sa.Column('autor', sa.String(length=200), nullable=False, comment='Autor da anotação (temporário até JWT).'),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_tramitacoes_projeto_id'), 'projeto_tramitacoes', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projeto_tramitacoes_projeto_id'), table_name='projeto_tramitacoes')
    op.drop_table('projeto_tramitacoes')
    # ### end Alembic commands ###
