"""Consolidate Servidor lotacao_id

Revision ID: 155b824010ab
Revises: db6a05c9a8f9
Create Date: 2026-05-08 20:02:14.486459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155b824010ab'
down_revision: Union[str, Sequence[str], None] = 'db6a05c9a8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('lotacao_id', sa.Integer(), nullable=False, comment='ID da Lotação do servidor.'))
    op.drop_constraint(op.f('servidores_secao_id_fkey'), 'servidores', type_='foreignkey')
    op.drop_constraint(op.f('servidores_unidade_lotacao_id_fkey'), 'servidores', type_='foreignkey')
    op.drop_constraint(op.f('servidores_departamento_id_fkey'), 'servidores', type_='foreignkey')
    op.create_foreign_key(None, 'servidores', 'unidades_organizacionais', ['lotacao_id'], ['id'])
    op.drop_column('servidores', 'secao_id')
    op.drop_column('servidores', 'departamento_id')
    op.drop_column('servidores', 'unidade_lotacao_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('unidade_lotacao_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID da Unidade de Lotação.'))
    op.add_column('servidores', sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID do Departamento.'))
    op.add_column('servidores', sa.Column('secao_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID da Seção.'))
    op.drop_constraint(None, 'servidores', type_='foreignkey')
    op.create_foreign_key(op.f('servidores_departamento_id_fkey'), 'servidores', 'unidades_organizacionais', ['departamento_id'], ['id'])
    op.create_foreign_key(op.f('servidores_unidade_lotacao_id_fkey'), 'servidores', 'unidades_organizacionais', ['unidade_lotacao_id'], ['id'])
    op.create_foreign_key(op.f('servidores_secao_id_fkey'), 'servidores', 'unidades_organizacionais', ['secao_id'], ['id'])
    op.drop_column('servidores', 'lotacao_id')
    # ### end Alembic commands ###
