"""Add tipo_catalogo and codigo_catalogo to ItemContrato

Revision ID: 176677e12337
Revises: 690dadd6b8f3
Create Date: 2026-05-06 14:47:53.837137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176677e12337'
down_revision: Union[str, Sequence[str], None] = '690dadd6b8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_contrato', sa.Column('tipo_catalogo', sa.String(length=10), nullable=True, comment="Tipo de catálogo: 'CATMAT' (material) ou 'CATSER' (serviço)."))
    op.add_column('item_contrato', sa.Column('codigo_catalogo', sa.String(length=50), nullable=True, comment='Código numérico do catálogo (ComprasNet).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_contrato', 'codigo_catalogo')
    op.drop_column('item_contrato', 'tipo_catalogo')
    # ### end Alembic commands ###
