"""add_complexidade_to_contrato

Revision ID: 28da846a4018
Revises: 7ba58f82ee07
Create Date: 2026-05-29 14:04:25.721288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28da846a4018'
down_revision: Union[str, Sequence[str], None] = '7ba58f82ee07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar o tipo ENUM explicitamente no Postgres
    complexidade_enum = sa.Enum('simples', 'intermediaria', 'complexa', name='complexidade_contrato_enum')
    complexidade_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('contratos', sa.Column('complexidade', complexidade_enum, server_default='simples', nullable=False, comment='Complexidade do contrato: simples, intermediaria ou complexa.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'complexidade')
    
    # Remover o tipo ENUM no Postgres
    complexidade_enum = sa.Enum('simples', 'intermediaria', 'complexa', name='complexidade_contrato_enum')
    complexidade_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
