"""Adicionando email_funcional ao Servidor

Revision ID: 2d4ee48ba8a7
Revises: 36717883afb7
Create Date: 2026-05-08 16:21:34.831098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4ee48ba8a7'
down_revision: Union[str, Sequence[str], None] = '36717883afb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('email_funcional', sa.String(length=200), nullable=True, comment='E-mail funcional do servidor.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servidores', 'email_funcional')
    # ### end Alembic commands ###
