"""cria_tabela_configuracao_sistema

Revision ID: 306a2636aecb
Revises: fbc8caaf067b
Create Date: 2026-04-21 11:43:07.250417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306a2636aecb'
down_revision: Union[str, Sequence[str], None] = 'fbc8caaf067b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_sistema',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_orgao', sa.String(length=255), nullable=False, comment='Nome do órgão para exibição na Top Bar'),
    sa.Column('cor_primaria', sa.String(length=20), nullable=False, comment='Cor primária do sistema em HEX (ex: #C4A75C)'),
    sa.Column('logo_url', sa.Text(), nullable=True, comment='Logotipo do órgão em Base64 ou URL da imagem'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes_sistema')
    # ### end Alembic commands ###
