"""Unificando estrutura organizacional em tabela unica

Revision ID: 36717883afb7
Revises: 565e45aa8da5
Create Date: 2026-05-08 15:27:07.541068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36717883afb7'
down_revision: Union[str, Sequence[str], None] = '565e45aa8da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create the new unified table
    op.create_table('unidades_organizacionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )

    # 2. Drop old FK constraints from association tables FIRST
    op.drop_constraint(op.f('pdtic_departamento_departamento_id_fkey'), 'pdtic_departamento', type_='foreignkey')
    op.drop_constraint(op.f('pdtic_unidade_demandante_unidade_demandante_id_fkey'), 'pdtic_unidade_demandante', type_='foreignkey')
    op.drop_constraint(op.f('pdtic_unidade_responsavel_unidade_responsavel_id_fkey'), 'pdtic_unidade_responsavel', type_='foreignkey')

    # 3. Drop old columns from association tables
    op.drop_column('pdtic_departamento', 'departamento_id')
    op.drop_column('pdtic_unidade_demandante', 'unidade_demandante_id')
    op.drop_column('pdtic_unidade_responsavel', 'unidade_responsavel_id')

    # 4. Drop old entity tables (now safe — no FKs pointing to them)
    op.drop_table('unidades_responsaveis')
    op.drop_table('unidades_demandantes')
    op.drop_table('departamentos_org')

    # 5. Add new columns + FKs pointing to unified table
    op.add_column('pdtic_departamento', sa.Column('unidade_org_id', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('pdtic_departamento', 'unidade_org_id', server_default=None)
    op.create_foreign_key(None, 'pdtic_departamento', 'unidades_organizacionais', ['unidade_org_id'], ['id'], ondelete='CASCADE')

    op.add_column('pdtic_unidade_demandante', sa.Column('unidade_org_id', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('pdtic_unidade_demandante', 'unidade_org_id', server_default=None)
    op.create_foreign_key(None, 'pdtic_unidade_demandante', 'unidades_organizacionais', ['unidade_org_id'], ['id'], ondelete='CASCADE')

    op.add_column('pdtic_unidade_responsavel', sa.Column('unidade_org_id', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('pdtic_unidade_responsavel', 'unidade_org_id', server_default=None)
    op.create_foreign_key(None, 'pdtic_unidade_responsavel', 'unidades_organizacionais', ['unidade_org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdtic_unidade_responsavel', sa.Column('unidade_responsavel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pdtic_unidade_responsavel', type_='foreignkey')
    op.create_foreign_key(op.f('pdtic_unidade_responsavel_unidade_responsavel_id_fkey'), 'pdtic_unidade_responsavel', 'unidades_responsaveis', ['unidade_responsavel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pdtic_unidade_responsavel', 'unidade_org_id')
    op.add_column('pdtic_unidade_demandante', sa.Column('unidade_demandante_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pdtic_unidade_demandante', type_='foreignkey')
    op.create_foreign_key(op.f('pdtic_unidade_demandante_unidade_demandante_id_fkey'), 'pdtic_unidade_demandante', 'unidades_demandantes', ['unidade_demandante_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pdtic_unidade_demandante', 'unidade_org_id')
    op.add_column('pdtic_departamento', sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pdtic_departamento', type_='foreignkey')
    op.create_foreign_key(op.f('pdtic_departamento_departamento_id_fkey'), 'pdtic_departamento', 'departamentos_org', ['departamento_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pdtic_departamento', 'unidade_org_id')
    op.create_table('departamentos_org',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('departamentos_org_pkey')),
    sa.UniqueConstraint('nome', name=op.f('departamentos_org_nome_key'))
    )
    op.create_table('unidades_demandantes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('unidades_demandantes_pkey')),
    sa.UniqueConstraint('nome', name=op.f('unidades_demandantes_nome_key'))
    )
    op.create_table('unidades_responsaveis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('unidades_responsaveis_pkey')),
    sa.UniqueConstraint('nome', name=op.f('unidades_responsaveis_nome_key'))
    )
    op.drop_table('unidades_organizacionais')
    # ### end Alembic commands ###
