"""add telefone to fornecedor

Revision ID: 390b919c1902
Revises: c1d2e3f4a5b6
Create Date: 2026-05-14 18:05:16.269357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390b919c1902'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogo_produtos', 'nome',
               existing_type=sa.VARCHAR(length=300),
               comment='Nome do produto/serviço de TI.',
               existing_nullable=False)
    op.alter_column('contratos', 'fornecedor_id',
               existing_type=sa.INTEGER(),
               comment='Fornecedor vinculado ao contrato (FK para fornecedores).',
               existing_nullable=True)
    op.alter_column('contratos', 'tipo_fornecedor_contrato',
               existing_type=sa.VARCHAR(length=30),
               comment='Tipo: REVENDEDOR, FABRICANTE ou REVENDEDOR_E_FABRICANTE.',
               existing_nullable=True)
    op.add_column('fornecedores', sa.Column('telefone', sa.String(length=50), nullable=True))
    op.alter_column('fornecedores', 'natureza',
               existing_type=postgresql.ENUM('PESSOA_FISICA', 'PESSOA_JURIDICA', name='natureza_fornecedor_enum'),
               comment='Pessoa Física ou Pessoa Jurídica.',
               existing_nullable=False)
    op.alter_column('fornecedores', 'documento',
               existing_type=sa.VARCHAR(length=18),
               comment='CPF (PF) ou CNPJ (PJ).',
               existing_nullable=True)
    op.alter_column('fornecedores', 'contatos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Lista de {nome, telefone, email, cargo}.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fornecedores', 'contatos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Lista de {nome, telefone, email, cargo}.',
               existing_nullable=True)
    op.alter_column('fornecedores', 'documento',
               existing_type=sa.VARCHAR(length=18),
               comment=None,
               existing_comment='CPF (PF) ou CNPJ (PJ).',
               existing_nullable=True)
    op.alter_column('fornecedores', 'natureza',
               existing_type=postgresql.ENUM('PESSOA_FISICA', 'PESSOA_JURIDICA', name='natureza_fornecedor_enum'),
               comment=None,
               existing_comment='Pessoa Física ou Pessoa Jurídica.',
               existing_nullable=False)
    op.drop_column('fornecedores', 'telefone')
    op.alter_column('contratos', 'tipo_fornecedor_contrato',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Tipo: REVENDEDOR, FABRICANTE ou REVENDEDOR_E_FABRICANTE.',
               existing_nullable=True)
    op.alter_column('contratos', 'fornecedor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Fornecedor vinculado ao contrato (FK para fornecedores).',
               existing_nullable=True)
    op.alter_column('catalogo_produtos', 'nome',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Nome do produto/serviço de TI.',
               existing_nullable=False)
    # ### end Alembic commands ###
