"""add_comentarios_artefato_table

Revision ID: 3c9029f7bd3f
Revises: 0191717a7693
Create Date: 2026-04-08 16:52:59.735051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9029f7bd3f'
down_revision: Union[str, Sequence[str], None] = '0191717a7693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios_artefato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artefato_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False, comment='Texto do comentário/observação.'),
    sa.Column('autor', sa.String(length=200), nullable=False, comment='Autor do comentário (temporário até JWT).'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artefato_id'], ['artefatos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_artefato_artefato_id'), 'comentarios_artefato', ['artefato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comentarios_artefato_artefato_id'), table_name='comentarios_artefato')
    op.drop_table('comentarios_artefato')
    # ### end Alembic commands ###
