"""Refatorando lotacao para unidades organizacionais no Servidor

Revision ID: 3e31bec3acdb
Revises: 2d4ee48ba8a7
Create Date: 2026-05-08 16:45:07.604774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e31bec3acdb'
down_revision: Union[str, Sequence[str], None] = '2d4ee48ba8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('departamento_id', sa.Integer(), nullable=False, comment='ID do Departamento.'))
    op.add_column('servidores', sa.Column('unidade_lotacao_id', sa.Integer(), nullable=True, comment='ID da Unidade de Lotação.'))
    op.add_column('servidores', sa.Column('secao_id', sa.Integer(), nullable=True, comment='ID da Seção.'))
    op.create_foreign_key(None, 'servidores', 'unidades_organizacionais', ['unidade_lotacao_id'], ['id'])
    op.create_foreign_key(None, 'servidores', 'unidades_organizacionais', ['secao_id'], ['id'])
    op.create_foreign_key(None, 'servidores', 'unidades_organizacionais', ['departamento_id'], ['id'])
    op.drop_column('servidores', 'lotacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('lotacao', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Unidade de lotação (ex: DTI, Gabinete).'))
    op.drop_constraint(None, 'servidores', type_='foreignkey')
    op.drop_constraint(None, 'servidores', type_='foreignkey')
    op.drop_constraint(None, 'servidores', type_='foreignkey')
    op.drop_column('servidores', 'secao_id')
    op.drop_column('servidores', 'unidade_lotacao_id')
    op.drop_column('servidores', 'departamento_id')
    # ### end Alembic commands ###
