"""initial_schema

Revision ID: 4cd4bf142919
Revises: 
Create Date: 2026-04-01 15:57:02.966523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd4bf142919'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacc_exercicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ano >= 2000 AND ano <= 2100', name='ck_exercicio_ano_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    op.create_table('pdtic_periodos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano_inicio', sa.Integer(), nullable=False),
    sa.Column('ano_fim', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ano_fim > ano_inicio', name='ck_periodo_anos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_inicio', 'ano_fim', name='uq_periodo_intervalo')
    )
    op.create_table('servidores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=False, comment='Matrícula funcional do servidor.'),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=False),
    sa.Column('funcao', sa.String(length=200), nullable=True, comment='Função comissionada ou de confiança, se houver.'),
    sa.Column('lotacao', sa.String(length=200), nullable=False, comment='Unidade de lotação (ex: DTI, Gabinete).'),
    sa.Column('perfil_acesso', sa.String(length=100), nullable=True, comment='Perfil de acesso ao sistema (futuro RBAC).'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servidores_matricula'), 'servidores', ['matricula'], unique=True)
    op.create_table('pacc_revisoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('numero_revisao', sa.Integer(), nullable=False),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_id'], ['pacc_exercicios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercicio_id', 'numero_revisao', name='uq_revisao_pacc_por_exercicio')
    )
    op.create_table('pdtic_revisoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('numero_revisao', sa.Integer(), nullable=False),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['pdtic_periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'numero_revisao', name='uq_revisao_por_periodo')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('processo_sei', sa.String(length=50), nullable=False, comment='Número do processo SEI vinculado ao projeto.'),
    sa.Column('complexidade', sa.Enum('baixa', 'media', 'alta', name='complexidade_projeto_enum'), nullable=False),
    sa.Column('catmat', sa.String(length=50), nullable=True, comment='Código CATMAT (material) do ComprasNet.'),
    sa.Column('catser', sa.String(length=50), nullable=True, comment='Código CATSER (serviço) do ComprasNet.'),
    sa.Column('status', sa.Enum('Em elaboração', 'Pronto para contratação', 'Em licitação', 'Licitação concluída', 'Suspenso', 'Cancelado', name='status_projeto_enum'), nullable=False),
    sa.Column('integrante_requisitante_id', sa.Integer(), nullable=True, comment='Integrante requisitante da equipe de planejamento.'),
    sa.Column('integrante_tecnico_id', sa.Integer(), nullable=True, comment='Integrante técnico da equipe de planejamento.'),
    sa.Column('integrante_administrativo_id', sa.Integer(), nullable=True, comment='Integrante administrativo da equipe de planejamento.'),
    sa.Column('data_envio_licitacao', sa.Date(), nullable=True, comment='Data em que o projeto foi enviado para a área de licitação.'),
    sa.Column('situacao_licitacao_texto', sa.Text(), nullable=True, comment='Descrição livre do andamento na área de compras/licitação.'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integrante_administrativo_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integrante_requisitante_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integrante_tecnico_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processo_sei'),
    sa.UniqueConstraint('processo_sei', name='uq_projeto_processo_sei')
    )
    op.create_table('artefatos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DFD', 'ETP', 'Mapa de Riscos', 'Estimativa de Custos e Orçamento', 'TR', name='tipo_artefato_enum'), nullable=False),
    sa.Column('status', sa.Enum('Não iniciado', 'Iniciado', 'Concluído', name='status_artefato_enum'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True, comment='Preenchida quando o artefato é iniciado.'),
    sa.Column('data_conclusao', sa.Date(), nullable=True, comment='Preenchida quando o artefato é concluído.'),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'tipo', name='uq_artefato_por_projeto_tipo')
    )
    op.create_table('pdtic_acoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_acao', sa.String(length=20), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('revisao_inclusao_id', sa.Integer(), nullable=False, comment='Revisão em que esta versão da ação foi criada/introduzida.'),
    sa.Column('revisao_exclusao_id', sa.Integer(), nullable=True, comment='Revisão em que esta ação foi logicamente excluída.'),
    sa.Column('acao_pai_id', sa.Integer(), nullable=True, comment='Aponta para a versão anterior quando esta ação é uma revisão de outra.'),
    sa.Column('departamento', sa.String(length=200), nullable=False),
    sa.Column('unidade_demandante', sa.String(length=200), nullable=False),
    sa.Column('unidade_responsavel', sa.String(length=200), nullable=False),
    sa.Column('necessidade', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo_necessidade', sa.Enum('hardware', 'software', 'servico', 'comunicacao', 'capacitacao', 'outros', name='tipo_necessidade_enum'), nullable=False),
    sa.Column('status', sa.Enum('Não iniciada', 'Em andamento', 'Contratada', name='status_acao_enum'), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('indicador', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.String(length=100), nullable=True),
    sa.Column('total_gut', sa.Integer(), nullable=False),
    sa.Column('previsao_contratacao', sa.String(length=10), nullable=True, comment='Formato MM/YYYY'),
    sa.Column('previsao_renovacao', sa.String(length=10), nullable=True, comment='Formato MM/YYYY'),
    sa.Column('valores_investimento', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ex: {"2024": 100000.00, "2025": 50000.00}'),
    sa.Column('valores_custeio', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ex: {"2024": 30000.00}'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_gut >= 0 AND total_gut <= 125', name='ck_acao_total_gut_range'),
    sa.ForeignKeyConstraint(['acao_pai_id'], ['pdtic_acoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['pdtic_periodos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revisao_exclusao_id'], ['pdtic_revisoes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revisao_inclusao_id'], ['pdtic_revisoes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_datas_artefato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artefato_id', sa.Integer(), nullable=False),
    sa.Column('tipo_data_alterada', sa.Enum('data_inicio', 'data_conclusao', name='tipo_data_alterada_enum'), nullable=False),
    sa.Column('data_antiga', sa.Date(), nullable=False),
    sa.Column('data_nova', sa.Date(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False, comment='Justificativa obrigatória para a alteração de data.'),
    sa.Column('data_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp automático do momento da alteração.'),
    sa.ForeignKeyConstraint(['artefato_id'], ['artefatos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacc_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_item', sa.String(length=20), nullable=False, comment='Número sequencial do item (ex: 1, 2, 3)'),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('revisao_inclusao_id', sa.Integer(), nullable=False, comment='Revisão em que esta versão do item foi criada/introduzida.'),
    sa.Column('revisao_exclusao_id', sa.Integer(), nullable=True, comment='Revisão em que este item foi logicamente excluído.'),
    sa.Column('item_pai_id', sa.Integer(), nullable=True, comment='Aponta para a versão anterior quando este item é uma revisão de outro.'),
    sa.Column('acao_pdtic_id', sa.Integer(), nullable=False, comment='Ação do PDTIC à qual este item de contratação está vinculado.'),
    sa.Column('descricao_demanda', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.String(length=100), nullable=False, comment='Quantidade estimada (ex: "1", "200", "diversos")'),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=False, comment='Valor estimado da contratação em R$'),
    sa.Column('processo_sei', sa.String(length=50), nullable=True, comment='Número do processo SEI (ex: "00052-00032300/2024-09")'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_estimado >= 0', name='ck_item_valor_estimado_positivo'),
    sa.ForeignKeyConstraint(['acao_pdtic_id'], ['pdtic_acoes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['pacc_exercicios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pai_id'], ['pacc_itens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revisao_exclusao_id'], ['pacc_revisoes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revisao_inclusao_id'], ['pacc_revisoes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto_acao_pdtic',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('acao_pdtic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_pdtic_id'], ['pdtic_acoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('projeto_id', 'acao_pdtic_id')
    )
    op.create_table('projeto_item_pacc',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('item_pacc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_pacc_id'], ['pacc_itens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('projeto_id', 'item_pacc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto_item_pacc')
    op.drop_table('projeto_acao_pdtic')
    op.drop_table('pacc_itens')
    op.drop_table('historico_datas_artefato')
    op.drop_table('pdtic_acoes')
    op.drop_table('artefatos')
    op.drop_table('projetos')
    op.drop_table('pdtic_revisoes')
    op.drop_table('pacc_revisoes')
    op.drop_index(op.f('ix_servidores_matricula'), table_name='servidores')
    op.drop_table('servidores')
    op.drop_table('pdtic_periodos')
    op.drop_table('pacc_exercicios')
    # ### end Alembic commands ###
