"""add_tabela_usuarios

Revision ID: 4ec68388421d
Revises: 306a2636aecb
Create Date: 2026-04-21 18:36:39.955587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec68388421d'
down_revision: Union[str, Sequence[str], None] = '306a2636aecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome completo do usuário'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='E-mail institucional (login único)'),
    sa.Column('senha_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt da senha do usuário'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica se o usuário está ativo no sistema'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
