"""Add tipo to CatalogoProduto and catalogo_produto_id to ItemContrato

Revision ID: 50ec3dbcbf57
Revises: d71ccf2fce02
Create Date: 2026-05-19 14:34:26.642552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ec3dbcbf57'
down_revision: Union[str, Sequence[str], None] = 'd71ccf2fce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_produtos', sa.Column('tipo', sa.String(length=20), server_default='PRODUTO', nullable=False, comment='Tipo do item: PRODUTO ou SERVICO.'))
    op.add_column('item_contrato', sa.Column('catalogo_produto_id', sa.Integer(), nullable=True, comment='Referência ao item padronizado do Catálogo de Produtos/Serviços.'))
    op.create_index(op.f('ix_item_contrato_catalogo_produto_id'), 'item_contrato', ['catalogo_produto_id'], unique=False)
    op.create_foreign_key(None, 'item_contrato', 'catalogo_produtos', ['catalogo_produto_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_contrato', type_='foreignkey')
    op.drop_index(op.f('ix_item_contrato_catalogo_produto_id'), table_name='item_contrato')
    op.drop_column('item_contrato', 'catalogo_produto_id')
    op.drop_column('catalogo_produtos', 'tipo')
    # ### end Alembic commands ###
