"""Refatorando PDTIC org units para N:N

Revision ID: 565e45aa8da5
Revises: a20375ca5f63
Create Date: 2026-05-08 14:45:44.949526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565e45aa8da5'
down_revision: Union[str, Sequence[str], None] = 'a20375ca5f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdtic_departamento',
    sa.Column('acao_pdtic_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_pdtic_id'], ['pdtic_acoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos_org.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('acao_pdtic_id', 'departamento_id')
    )
    op.create_table('pdtic_unidade_demandante',
    sa.Column('acao_pdtic_id', sa.Integer(), nullable=False),
    sa.Column('unidade_demandante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_pdtic_id'], ['pdtic_acoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_demandante_id'], ['unidades_demandantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('acao_pdtic_id', 'unidade_demandante_id')
    )
    op.create_table('pdtic_unidade_responsavel',
    sa.Column('acao_pdtic_id', sa.Integer(), nullable=False),
    sa.Column('unidade_responsavel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_pdtic_id'], ['pdtic_acoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_responsavel_id'], ['unidades_responsaveis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('acao_pdtic_id', 'unidade_responsavel_id')
    )
    op.drop_constraint(op.f('pdtic_acoes_unidade_responsavel_id_fkey'), 'pdtic_acoes', type_='foreignkey')
    op.drop_constraint(op.f('pdtic_acoes_unidade_demandante_id_fkey'), 'pdtic_acoes', type_='foreignkey')
    op.drop_constraint(op.f('pdtic_acoes_departamento_id_fkey'), 'pdtic_acoes', type_='foreignkey')
    op.drop_column('pdtic_acoes', 'unidade_demandante_id')
    op.drop_column('pdtic_acoes', 'departamento_id')
    op.drop_column('pdtic_acoes', 'unidade_responsavel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdtic_acoes', sa.Column('unidade_responsavel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pdtic_acoes', sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pdtic_acoes', sa.Column('unidade_demandante_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pdtic_acoes_departamento_id_fkey'), 'pdtic_acoes', 'departamentos_org', ['departamento_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('pdtic_acoes_unidade_demandante_id_fkey'), 'pdtic_acoes', 'unidades_demandantes', ['unidade_demandante_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('pdtic_acoes_unidade_responsavel_id_fkey'), 'pdtic_acoes', 'unidades_responsaveis', ['unidade_responsavel_id'], ['id'], ondelete='SET NULL')
    op.drop_table('pdtic_unidade_responsavel')
    op.drop_table('pdtic_unidade_demandante')
    op.drop_table('pdtic_departamento')
    # ### end Alembic commands ###
