"""add tipo_contratacao to contrato

Revision ID: 5e20bcce48c9
Revises: a8b9c0d1e2f3
Create Date: 2026-05-21 16:03:34.637657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e20bcce48c9'
down_revision: Union[str, Sequence[str], None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('tipo_contratacao', sa.String(length=100), nullable=True, comment='Tipo de contratação (ex: Dispensa, Inexigibilidade, Pregão, etc.).'))
    op.alter_column('projetos', 'observacoes',
               existing_type=sa.TEXT(),
               comment='Anotações gerais e informações adicionais sobre o projeto.',
               existing_nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail institucional',
               existing_comment='E-mail institucional (login único)',
               existing_nullable=False)
    op.alter_column('usuarios', 'matricula',
               existing_type=sa.VARCHAR(length=30),
               comment='Matrícula institucional do servidor (login único, sanitizada)',
               existing_nullable=True)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash bcrypt da senha — NULL indica conta pendente de ativação',
               existing_comment='Hash bcrypt da senha do usuário',
               existing_nullable=True)
    op.alter_column('usuarios', 'token_ativacao',
               existing_type=sa.VARCHAR(length=500),
               comment='Hash do token JWT de ativação/reset de uso único',
               existing_nullable=True)
    op.alter_column('usuarios', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'COMUM', 'GESTOR', name='role_usuario_enum'),
               comment='Papel do usuário: ADMIN, GESTOR ou COMUM',
               existing_comment='Papel do usuário: ADMIN ou COMUM',
               existing_nullable=False,
               existing_server_default=sa.text("'COMUM'::role_usuario_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'COMUM', 'GESTOR', name='role_usuario_enum'),
               comment='Papel do usuário: ADMIN ou COMUM',
               existing_comment='Papel do usuário: ADMIN, GESTOR ou COMUM',
               existing_nullable=False,
               existing_server_default=sa.text("'COMUM'::role_usuario_enum"))
    op.alter_column('usuarios', 'token_ativacao',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Hash do token JWT de ativação/reset de uso único',
               existing_nullable=True)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash bcrypt da senha do usuário',
               existing_comment='Hash bcrypt da senha — NULL indica conta pendente de ativação',
               existing_nullable=True)
    op.alter_column('usuarios', 'matricula',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Matrícula institucional do servidor (login único, sanitizada)',
               existing_nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail institucional (login único)',
               existing_comment='E-mail institucional',
               existing_nullable=False)
    op.alter_column('projetos', 'observacoes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Anotações gerais e informações adicionais sobre o projeto.',
               existing_nullable=True)
    op.drop_column('contratos', 'tipo_contratacao')
    # ### end Alembic commands ###
