"""add_item_contrato

Revision ID: 60aefd345bc8
Revises: c6a2e629625e
Create Date: 2026-04-30 16:04:06.206087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60aefd345bc8'
down_revision: Union[str, Sequence[str], None] = 'c6a2e629625e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_contrato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('objeto_contratado', sa.String(length=500), nullable=False, comment='Descrição detalhada do item/produto/serviço contratado.'),
    sa.Column('quantidade', sa.Integer(), nullable=False, comment='Quantidade de itens.'),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=False, comment='Valor unitário do item.'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_contrato_contrato_id'), 'item_contrato', ['contrato_id'], unique=False)
    op.drop_column('contratos', 'valor_custeio')
    op.drop_column('contratos', 'tecnologia_utilizada')
    op.drop_column('contratos', 'valor_investimento')
    op.drop_column('contratos', 'quantidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False, comment='Quantidade de itens/licenças/unidades contratadas.'))
    op.add_column('contratos', sa.Column('valor_investimento', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Valor de investimento (CAPEX).'))
    op.add_column('contratos', sa.Column('tecnologia_utilizada', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Descrição livre da tecnologia contratada.'))
    op.add_column('contratos', sa.Column('valor_custeio', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Valor de custeio (OPEX).'))
    op.drop_index(op.f('ix_item_contrato_contrato_id'), table_name='item_contrato')
    op.drop_table('item_contrato')
    # ### end Alembic commands ###
