"""alter_pdtic_dates_to_date_type

Revision ID: 615a65f83932
Revises: 155b824010ab
Create Date: 2026-05-11 17:34:01.587474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615a65f83932'
down_revision: Union[str, Sequence[str], None] = '155b824010ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdtic_acoes', 'previsao_contratacao',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_comment='Formato MM/YYYY',
               existing_nullable=True,
               postgresql_using="to_date(previsao_contratacao, 'MM/YYYY')")
    op.alter_column('pdtic_acoes', 'previsao_renovacao',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_comment='Formato MM/YYYY',
               existing_nullable=True,
               postgresql_using="to_date(previsao_renovacao, 'MM/YYYY')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdtic_acoes', 'previsao_renovacao',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               comment='Formato MM/YYYY',
               existing_comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_nullable=True)
    op.alter_column('pdtic_acoes', 'previsao_contratacao',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               comment='Formato MM/YYYY',
               existing_comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_nullable=True)
    # ### end Alembic commands ###
