"""remove_perfil_acesso_from_servidores

Revision ID: 690dadd6b8f3
Revises: d1e2f3a4b5c6
Create Date: 2026-05-04 17:25:31.374876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '690dadd6b8f3'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdtic_acoes', 'tipo_necessidade',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment='Lista de tipos de necessidade: hardware, software, servico, etc.',
               existing_nullable=False)
    op.drop_column('servidores', 'perfil_acesso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('perfil_acesso', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Perfil de acesso ao sistema (futuro RBAC).'))
    op.alter_column('pdtic_acoes', 'tipo_necessidade',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment=None,
               existing_comment='Lista de tipos de necessidade: hardware, software, servico, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
