"""Split numero_contrato into numero and ano

Revision ID: 6dbfe1a3fe0d
Revises: 99197af3fcaf
Create Date: 2026-05-06 16:35:12.537930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbfe1a3fe0d'
down_revision: Union[str, Sequence[str], None] = '99197af3fcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('numero', sa.Integer(), nullable=False))
    op.add_column('contratos', sa.Column('ano', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_contratos_numero_contrato'), table_name='contratos')
    op.drop_constraint(op.f('uq_contrato_numero'), 'contratos', type_='unique')
    op.create_index(op.f('ix_contratos_ano'), 'contratos', ['ano'], unique=False)
    op.create_index(op.f('ix_contratos_numero'), 'contratos', ['numero'], unique=False)
    op.create_unique_constraint('uq_contrato_numero_ano', 'contratos', ['numero', 'ano'])
    op.drop_column('contratos', 'numero_contrato')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('numero_contrato', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Número do contrato no formato NN/YYYY.'))
    op.drop_constraint('uq_contrato_numero_ano', 'contratos', type_='unique')
    op.drop_index(op.f('ix_contratos_numero'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_ano'), table_name='contratos')
    op.create_unique_constraint(op.f('uq_contrato_numero'), 'contratos', ['numero_contrato'])
    op.create_index(op.f('ix_contratos_numero_contrato'), 'contratos', ['numero_contrato'], unique=True)
    op.drop_column('contratos', 'ano')
    op.drop_column('contratos', 'numero')
    # ### end Alembic commands ###
