"""Add prioridade in projetos

Revision ID: 6f370bd752a9
Revises: 95c234a9b4f8
Create Date: 2026-04-21 19:58:03.074677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f370bd752a9'
down_revision: Union[str, Sequence[str], None] = '95c234a9b4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('prioridade', sa.String(), server_default='media', nullable=False, comment='Prioridade: baixa, media, alta'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'prioridade')
    # ### end Alembic commands ###
