"""Refatoracao da Equipe de Planejamento 1:N

Revision ID: 7b27044f98f8
Revises: b3c4d5e6f7a9
Create Date: 2026-05-14 14:51:33.211519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b27044f98f8'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto_equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('Requisitante', 'Técnico', 'Administrativo', name='papel_projeto_enum'), nullable=False, comment='Papel do servidor na equipe.'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_equipe_projeto_id'), 'projeto_equipe', ['projeto_id'], unique=False)
    op.alter_column('projetos', 'prioridade',
               existing_type=sa.VARCHAR(),
               comment='Prioridade: baixa, media, alta. Nullable para projetos legados.',
               existing_comment='Prioridade: baixa, media, alta',
               existing_nullable=True,
               existing_server_default=sa.text("'media'::character varying"))
    op.alter_column('projetos', 'complexidade',
               existing_type=sa.VARCHAR(),
               comment='Complexidade: Simples, Intermediária ou Complexa. Nullable para projetos legados.',
               existing_comment='Complexidade: Simples, Intermediária ou Complexa',
               existing_nullable=True)
    op.alter_column('projetos', 'is_legado',
               existing_type=sa.BOOLEAN(),
               comment='Se True, projeto legado: pula artefatos, prioridade e complexidade.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # --- BACKFILL START ---
    op.execute("""
        INSERT INTO projeto_equipe (projeto_id, servidor_id, papel)
        SELECT id, integrante_requisitante_id, 'Requisitante' 
        FROM projetos 
        WHERE integrante_requisitante_id IS NOT NULL;
    """)
    op.execute("""
        INSERT INTO projeto_equipe (projeto_id, servidor_id, papel)
        SELECT id, integrante_tecnico_id, 'Técnico' 
        FROM projetos 
        WHERE integrante_tecnico_id IS NOT NULL;
    """)
    op.execute("""
        INSERT INTO projeto_equipe (projeto_id, servidor_id, papel)
        SELECT id, integrante_administrativo_id, 'Administrativo' 
        FROM projetos 
        WHERE integrante_administrativo_id IS NOT NULL;
    """)
    # --- BACKFILL END ---

    op.drop_constraint('projetos_integrante_administrativo_id_fkey', 'projetos', type_='foreignkey')
    op.drop_constraint('projetos_integrante_tecnico_id_fkey', 'projetos', type_='foreignkey')
    op.drop_constraint('projetos_integrante_requisitante_id_fkey', 'projetos', type_='foreignkey')
    op.drop_column('projetos', 'integrante_requisitante_id')
    op.drop_column('projetos', 'integrante_administrativo_id')
    op.drop_column('projetos', 'integrante_tecnico_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('integrante_tecnico_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Integrante técnico da equipe de planejamento.'))
    op.add_column('projetos', sa.Column('integrante_administrativo_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Integrante administrativo da equipe de planejamento.'))
    op.add_column('projetos', sa.Column('integrante_requisitante_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Integrante requisitante da equipe de planejamento.'))
    op.create_foreign_key(op.f('projetos_integrante_requisitante_id_fkey'), 'projetos', 'servidores', ['integrante_requisitante_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('projetos_integrante_tecnico_id_fkey'), 'projetos', 'servidores', ['integrante_tecnico_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('projetos_integrante_administrativo_id_fkey'), 'projetos', 'servidores', ['integrante_administrativo_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projetos', 'is_legado',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Se True, projeto legado: pula artefatos, prioridade e complexidade.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('projetos', 'complexidade',
               existing_type=sa.VARCHAR(),
               comment='Complexidade: Simples, Intermediária ou Complexa',
               existing_comment='Complexidade: Simples, Intermediária ou Complexa. Nullable para projetos legados.',
               existing_nullable=True)
    op.alter_column('projetos', 'prioridade',
               existing_type=sa.VARCHAR(),
               comment='Prioridade: baixa, media, alta',
               existing_comment='Prioridade: baixa, media, alta. Nullable para projetos legados.',
               existing_nullable=True,
               existing_server_default=sa.text("'media'::character varying"))
    op.drop_index(op.f('ix_projeto_equipe_projeto_id'), table_name='projeto_equipe')
    op.drop_table('projeto_equipe')
    # ### end Alembic commands ###
