"""remove_observacoes_from_contrato

Revision ID: 7ba58f82ee07
Revises: 94a109353b60
Create Date: 2026-05-29 07:52:44.123094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba58f82ee07'
down_revision: Union[str, Sequence[str], None] = '94a109353b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'observacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
