"""Add data_previsao_fim to artefatos

Revision ID: 859948796233
Revises: 877d6e021f1f
Create Date: 2026-04-23 08:55:52.219727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859948796233'
down_revision: Union[str, Sequence[str], None] = '877d6e021f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefatos', sa.Column('data_previsao_fim', sa.Date(), nullable=True, comment='Data de previsão de conclusão definida pelo usuário ao iniciar.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artefatos', 'data_previsao_fim')
    # ### end Alembic commands ###
