"""Make fabricante fields optional

Revision ID: 877d6e021f1f
Revises: c4d5e6f7a8b9
Create Date: 2026-04-22 18:57:58.487374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '877d6e021f1f'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('fabricantes', 'contato_nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('fabricantes', 'contato_cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('fabricantes', 'contato_telefone1',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('fabricantes', 'contato_email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fabricantes', 'contato_email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('fabricantes', 'contato_telefone1',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('fabricantes', 'contato_cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('fabricantes', 'contato_nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
