"""adicionar_is_titular_projeto_equipe

Revision ID: 9307020608f6
Revises: 7b27044f98f8
Create Date: 2026-05-14 15:26:39.745500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9307020608f6'
down_revision: Union[str, Sequence[str], None] = '7b27044f98f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Adicionar coluna com server_default para backfill seguro
    op.add_column('projeto_equipe', sa.Column('is_titular', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='True = Titular; False = Substituto.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projeto_equipe', 'is_titular')
    # ### end Alembic commands ###
