"""Add complexidade string in projetos

Revision ID: 95c234a9b4f8
Revises: 42720cbe99f0
Create Date: 2026-04-21 19:54:48.741198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c234a9b4f8'
down_revision: Union[str, Sequence[str], None] = '42720cbe99f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projetos', 'complexidade',
               existing_type=postgresql.ENUM('baixa', 'media', 'alta', name='complexidade_projeto_enum'),
               type_=sa.String(),
               comment='Complexidade: Simples, Intermediária ou Complexa',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projetos', 'complexidade',
               existing_type=sa.String(),
               type_=postgresql.ENUM('baixa', 'media', 'alta', name='complexidade_projeto_enum'),
               comment=None,
               existing_comment='Complexidade: Simples, Intermediária ou Complexa',
               existing_nullable=False)
    # ### end Alembic commands ###
