"""Remove catmat and catser from Projeto

Revision ID: 99197af3fcaf
Revises: 176677e12337
Create Date: 2026-05-06 14:58:13.027672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99197af3fcaf'
down_revision: Union[str, Sequence[str], None] = '176677e12337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'catser')
    op.drop_column('projetos', 'catmat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('catmat', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Código CATMAT (material) do ComprasNet.'))
    op.add_column('projetos', sa.Column('catser', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Código CATSER (serviço) do ComprasNet.'))
    # ### end Alembic commands ###
