"""Drop data_previsao_fim from artefatos

Revision ID: a11e82e30de4
Revises: 859948796233
Create Date: 2026-04-23 09:50:29.142442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a11e82e30de4'
down_revision: Union[str, Sequence[str], None] = '859948796233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artefatos', 'data_previsao_fim')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefatos', sa.Column('data_previsao_fim', sa.DATE(), autoincrement=False, nullable=True, comment='Data de previsão de conclusão definida pelo usuário ao iniciar.'))
    # ### end Alembic commands ###
