"""Add estrutura_org e fks pdtic

Revision ID: a20375ca5f63
Revises: f49d0e90d599
Create Date: 2026-05-07 17:40:36.211340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20375ca5f63'
down_revision: Union[str, Sequence[str], None] = 'f49d0e90d599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos_org',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidades_demandantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidades_responsaveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('pdtic_acoes', sa.Column('departamento_id', sa.Integer(), nullable=True))
    op.add_column('pdtic_acoes', sa.Column('unidade_demandante_id', sa.Integer(), nullable=True))
    op.add_column('pdtic_acoes', sa.Column('unidade_responsavel_id', sa.Integer(), nullable=True))
    op.alter_column('pdtic_acoes', 'departamento',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('pdtic_acoes', 'unidade_demandante',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('pdtic_acoes', 'unidade_responsavel',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_foreign_key(None, 'pdtic_acoes', 'departamentos_org', ['departamento_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pdtic_acoes', 'unidades_demandantes', ['unidade_demandante_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pdtic_acoes', 'unidades_responsaveis', ['unidade_responsavel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdtic_acoes', type_='foreignkey')
    op.drop_constraint(None, 'pdtic_acoes', type_='foreignkey')
    op.drop_constraint(None, 'pdtic_acoes', type_='foreignkey')
    op.alter_column('pdtic_acoes', 'unidade_responsavel',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('pdtic_acoes', 'unidade_demandante',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('pdtic_acoes', 'departamento',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('pdtic_acoes', 'unidade_responsavel_id')
    op.drop_column('pdtic_acoes', 'unidade_demandante_id')
    op.drop_column('pdtic_acoes', 'departamento_id')
    op.drop_table('unidades_responsaveis')
    op.drop_table('unidades_demandantes')
    op.drop_table('departamentos_org')
    # ### end Alembic commands ###
