"""Add observacoes_fase_externa table

Revision ID: c6a2e629625e
Revises: b2c3d4e5f6a7
Create Date: 2026-04-29 20:03:10.980134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a2e629625e'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observacoes_fase_externa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observacoes_fase_externa_projeto_id'), 'observacoes_fase_externa', ['projeto_id'], unique=False)
    op.alter_column('aditivos', 'contrato_id',
               existing_type=sa.INTEGER(),
               comment='Contrato ao qual este aditivo pertence.',
               existing_nullable=False)
    op.alter_column('aditivos', 'numero_aditivo',
               existing_type=sa.VARCHAR(length=100),
               comment="Identificação do aditivo (ex: '1º Termo Aditivo').",
               existing_nullable=False)
    op.alter_column('aditivos', 'data_inicio_vigencia',
               existing_type=sa.DATE(),
               comment='Data de início da nova vigência estabelecida pelo aditivo.',
               existing_nullable=False)
    op.alter_column('aditivos', 'data_fim_vigencia',
               existing_type=sa.DATE(),
               comment='Nova data de fim de vigência após o aditivo.',
               existing_nullable=False)
    op.alter_column('auditoria_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID do usuário que realizou a ação (nullable para operações de sistema)',
               existing_comment='ID do usuário que realizou a ação',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email do usuário no momento da ação (preservado mesmo se o usuário for deletado)',
               existing_comment='Email do usuário no momento da ação',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome da entidade/módulo afetado (ex: Contrato, Projeto, AcaoPdtic)',
               existing_comment='Nome da entidade/módulo afetado',
               existing_nullable=False)
    op.alter_column('auditoria_logs', 'entidade_id',
               existing_type=sa.INTEGER(),
               comment='ID do registro afetado na entidade',
               existing_comment='ID do registro afetado',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'detalhes',
               existing_type=sa.TEXT(),
               comment='Detalhes da operação em formato JSON (campos alterados, valores antigos/novos)',
               existing_comment='Detalhes da operação em formato JSON',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Endereço IP do cliente (IPv4 ou IPv6)',
               existing_comment='Endereço IP do cliente',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'metodo_http',
               existing_type=sa.VARCHAR(length=10),
               comment='Método HTTP utilizado (POST, PUT, PATCH, DELETE)',
               existing_comment='Método HTTP utilizado',
               existing_nullable=True)
    op.alter_column('contratos', 'empresa_id',
               existing_type=sa.INTEGER(),
               comment='Empresa contratada (FK para empresas).',
               existing_nullable=True)
    op.alter_column('contratos', 'data_inicio_vigencia',
               existing_type=sa.DATE(),
               comment='Data de início da vigência (pode diferir da assinatura).',
               existing_nullable=True)
    op.alter_column('contratos', 'vigencia_meses',
               existing_type=sa.INTEGER(),
               comment='Quantidade de meses de vigência original (calculado automaticamente).',
               existing_nullable=True)
    op.alter_column('contratos', 'prorrogacao_meses',
               existing_type=sa.INTEGER(),
               comment='Prorrogação total em meses acumulada via aditivos.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ no formato 00.000.000/0000-00.',
               existing_nullable=True)
    op.alter_column('empresas', 'servicos_ofertados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Lista de strings com os serviços ofertados pela empresa.',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_empresa_cnpj'), 'empresas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_empresa_cnpj'), 'empresas', ['cnpj'])
    op.alter_column('empresas', 'servicos_ofertados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Lista de strings com os serviços ofertados pela empresa.',
               existing_nullable=True)
    op.alter_column('empresas', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment=None,
               existing_comment='CNPJ no formato 00.000.000/0000-00.',
               existing_nullable=True)
    op.alter_column('contratos', 'prorrogacao_meses',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Prorrogação total em meses acumulada via aditivos.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('contratos', 'vigencia_meses',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade de meses de vigência original (calculado automaticamente).',
               existing_nullable=True)
    op.alter_column('contratos', 'data_inicio_vigencia',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de início da vigência (pode diferir da assinatura).',
               existing_nullable=True)
    op.alter_column('contratos', 'empresa_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Empresa contratada (FK para empresas).',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'metodo_http',
               existing_type=sa.VARCHAR(length=10),
               comment='Método HTTP utilizado',
               existing_comment='Método HTTP utilizado (POST, PUT, PATCH, DELETE)',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Endereço IP do cliente',
               existing_comment='Endereço IP do cliente (IPv4 ou IPv6)',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'detalhes',
               existing_type=sa.TEXT(),
               comment='Detalhes da operação em formato JSON',
               existing_comment='Detalhes da operação em formato JSON (campos alterados, valores antigos/novos)',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade_id',
               existing_type=sa.INTEGER(),
               comment='ID do registro afetado',
               existing_comment='ID do registro afetado na entidade',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome da entidade/módulo afetado',
               existing_comment='Nome da entidade/módulo afetado (ex: Contrato, Projeto, AcaoPdtic)',
               existing_nullable=False)
    op.alter_column('auditoria_logs', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email do usuário no momento da ação',
               existing_comment='Email do usuário no momento da ação (preservado mesmo se o usuário for deletado)',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID do usuário que realizou a ação',
               existing_comment='ID do usuário que realizou a ação (nullable para operações de sistema)',
               existing_nullable=True)
    op.alter_column('aditivos', 'data_fim_vigencia',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Nova data de fim de vigência após o aditivo.',
               existing_nullable=False)
    op.alter_column('aditivos', 'data_inicio_vigencia',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de início da nova vigência estabelecida pelo aditivo.',
               existing_nullable=False)
    op.alter_column('aditivos', 'numero_aditivo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Identificação do aditivo (ex: '1º Termo Aditivo').",
               existing_nullable=False)
    op.alter_column('aditivos', 'contrato_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Contrato ao qual este aditivo pertence.',
               existing_nullable=False)
    op.drop_index(op.f('ix_observacoes_fase_externa_projeto_id'), table_name='observacoes_fase_externa')
    op.drop_table('observacoes_fase_externa')
    # ### end Alembic commands ###
