"""alterar_datas_pdtic_para_string_mensal

Revision ID: d71ccf2fce02
Revises: 02d5934d6803
Create Date: 2026-05-18 19:41:21.552369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71ccf2fce02'
down_revision: Union[str, Sequence[str], None] = '02d5934d6803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdtic_acoes', 'previsao_contratacao',
               existing_type=sa.DATE(),
               type_=sa.String(length=7),
               comment='Data prevista (ISO: YYYY-MM)',
               existing_comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_nullable=True,
               postgresql_using="to_char(previsao_contratacao, 'YYYY-MM')")
    op.alter_column('pdtic_acoes', 'previsao_renovacao',
               existing_type=sa.DATE(),
               type_=sa.String(length=7),
               comment='Data prevista (ISO: YYYY-MM)',
               existing_comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_nullable=True,
               postgresql_using="to_char(previsao_renovacao, 'YYYY-MM')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdtic_acoes', 'previsao_renovacao',
               existing_type=sa.String(length=7),
               type_=sa.DATE(),
               comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_comment='Data prevista (ISO: YYYY-MM)',
               existing_nullable=True)
    op.alter_column('pdtic_acoes', 'previsao_contratacao',
               existing_type=sa.String(length=7),
               type_=sa.DATE(),
               comment='Data prevista (ISO: YYYY-MM-DD)',
               existing_comment='Data prevista (ISO: YYYY-MM)',
               existing_nullable=True)
    # ### end Alembic commands ###
