"""add_unidade_pai_id_hierarchy

Revision ID: db6a05c9a8f9
Revises: 3e31bec3acdb
Create Date: 2026-05-08 18:37:47.807264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6a05c9a8f9'
down_revision: Union[str, Sequence[str], None] = '3e31bec3acdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades_organizacionais', sa.Column('unidade_pai_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unidades_organizacionais', 'unidades_organizacionais', ['unidade_pai_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unidades_organizacionais', type_='foreignkey')
    op.drop_column('unidades_organizacionais', 'unidade_pai_id')
    # ### end Alembic commands ###
