"""cria_tabela_contratos

Revision ID: e0ff80644a3e
Revises: 4cd4bf142919
Create Date: 2026-04-01 17:33:14.655778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ff80644a3e'
down_revision: Union[str, Sequence[str], None] = '4cd4bf142919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_contrato', sa.String(length=20), nullable=False, comment='Número do contrato no formato NN/YYYY.'),
    sa.Column('projeto_id', sa.Integer(), nullable=False, comment="Projeto de origem (deve ter status 'Licitação concluída')."),
    sa.Column('empresa_contratada', sa.String(length=500), nullable=False, comment='Razão social da empresa contratada.'),
    sa.Column('fabricante', sa.String(length=300), nullable=True, comment='Fabricante do produto/solução, se aplicável.'),
    sa.Column('tipo_contrato', sa.Enum('Aquisição', 'Serviço continuado', 'Subscrição', name='tipo_contrato_enum'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False, comment='Quantidade de itens/licenças/unidades contratadas.'),
    sa.Column('tecnologia_utilizada', sa.String(length=500), nullable=True, comment='Descrição livre da tecnologia contratada.'),
    sa.Column('valor_investimento', sa.Numeric(precision=15, scale=2), nullable=False, comment='Valor de investimento (CAPEX).'),
    sa.Column('valor_custeio', sa.Numeric(precision=15, scale=2), nullable=False, comment='Valor de custeio (OPEX).'),
    sa.Column('prazo', sa.String(length=300), nullable=True, comment="Descrição do prazo (ex: '12 meses; 24 meses com suporte')."),
    sa.Column('data_assinatura', sa.Date(), nullable=False, comment='Data de assinatura do contrato.'),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=False, comment='Data de encerramento da vigência.'),
    sa.Column('situacao_atual', sa.Enum('Vigente', 'Extinto', 'Extinto, mas suporte vigente', name='situacao_contrato_enum'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True, comment='Gestor do contrato.'),
    sa.Column('fiscal_requisitante_id', sa.Integer(), nullable=True, comment='Fiscal requisitante do contrato.'),
    sa.Column('fiscal_tecnico_id', sa.Integer(), nullable=True, comment='Fiscal técnico do contrato.'),
    sa.Column('fiscal_administrativo_id', sa.Integer(), nullable=True, comment='Fiscal administrativo do contrato.'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_administrativo_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_requisitante_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_tecnico_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gestor_id'], ['servidores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato', name='uq_contrato_numero')
    )
    op.create_index(op.f('ix_contratos_numero_contrato'), 'contratos', ['numero_contrato'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_numero_contrato'), table_name='contratos')
    op.drop_table('contratos')
    # ### end Alembic commands ###
