"""Remove objeto_contratado

Revision ID: f19c4f52f38a
Revises: 50ec3dbcbf57
Create Date: 2026-05-19 15:09:52.168650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19c4f52f38a'
down_revision: Union[str, Sequence[str], None] = '50ec3dbcbf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_contrato', 'objeto_contratado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_contrato', sa.Column('objeto_contratado', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='Descrição detalhada do item/produto/serviço contratado.'))
    # ### end Alembic commands ###
