"""atualiza_modelo_contrato

Revision ID: fbc8caaf067b
Revises: 14c7f43da8b0
Create Date: 2026-04-21 10:49:39.548109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc8caaf067b'
down_revision: Union[str, Sequence[str], None] = '14c7f43da8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabricantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('contato_nome', sa.String(length=150), nullable=False),
    sa.Column('contato_cargo', sa.String(length=100), nullable=False),
    sa.Column('contato_telefone1', sa.String(length=30), nullable=False),
    sa.Column('contato_telefone2', sa.String(length=30), nullable=True),
    sa.Column('contato_email', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('gestor', 'fiscal_requisitante', 'fiscal_tecnico', 'fiscal_administrativo', name='papel_equipe_enum'), nullable=False, comment='Papel do servidor na equipe.'),
    sa.Column('is_titular', sa.Boolean(), nullable=False, comment='True = Titular; False = Substituto.'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrato_equipe_contrato_id'), 'contrato_equipe', ['contrato_id'], unique=False)
    op.add_column('contratos', sa.Column('fabricante_id', sa.Integer(), nullable=True, comment='Fabricante do produto/solução (FK para fabricantes).'))
    op.drop_constraint(op.f('contratos_gestor_id_fkey'), 'contratos', type_='foreignkey')
    op.drop_constraint(op.f('contratos_fiscal_requisitante_id_fkey'), 'contratos', type_='foreignkey')
    op.drop_constraint(op.f('contratos_fiscal_tecnico_id_fkey'), 'contratos', type_='foreignkey')
    op.drop_constraint(op.f('contratos_fiscal_administrativo_id_fkey'), 'contratos', type_='foreignkey')
    op.create_foreign_key(None, 'contratos', 'fabricantes', ['fabricante_id'], ['id'], ondelete='SET NULL')
    op.drop_column('contratos', 'fabricante')
    op.drop_column('contratos', 'fiscal_tecnico_id')
    op.drop_column('contratos', 'fiscal_requisitante_id')
    op.drop_column('contratos', 'fiscal_administrativo_id')
    op.drop_column('contratos', 'gestor_id')
    op.alter_column('pacc_itens', 'processo_sei',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               comment='Números dos processos SEI (ex: "00052-00032300/2024-09")',
               existing_comment='Número do processo SEI (ex: "00052-00032300/2024-09")',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacc_itens', 'processo_sei',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               comment='Número do processo SEI (ex: "00052-00032300/2024-09")',
               existing_comment='Números dos processos SEI (ex: "00052-00032300/2024-09")',
               existing_nullable=True)
    op.add_column('contratos', sa.Column('gestor_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Gestor do contrato.'))
    op.add_column('contratos', sa.Column('fiscal_administrativo_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Fiscal administrativo do contrato.'))
    op.add_column('contratos', sa.Column('fiscal_requisitante_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Fiscal requisitante do contrato.'))
    op.add_column('contratos', sa.Column('fiscal_tecnico_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Fiscal técnico do contrato.'))
    op.add_column('contratos', sa.Column('fabricante', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='Fabricante do produto/solução, se aplicável.'))
    op.drop_constraint(None, 'contratos', type_='foreignkey')
    op.create_foreign_key(op.f('contratos_fiscal_administrativo_id_fkey'), 'contratos', 'servidores', ['fiscal_administrativo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contratos_fiscal_tecnico_id_fkey'), 'contratos', 'servidores', ['fiscal_tecnico_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contratos_fiscal_requisitante_id_fkey'), 'contratos', 'servidores', ['fiscal_requisitante_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contratos_gestor_id_fkey'), 'contratos', 'servidores', ['gestor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('contratos', 'fabricante_id')
    op.drop_index(op.f('ix_contrato_equipe_contrato_id'), table_name='contrato_equipe')
    op.drop_table('contrato_equipe')
    op.drop_table('fabricantes')
    # ### end Alembic commands ###
